from __future__ import annotations

import re


CATEGORY_LABELS = {
    "register": {"de": "Matrik", "en": "Register", "cs": "Matrika"},
    "chronicle": {"de": "Chronik", "en": "Chronicle", "cs": "Kronika"},
    "deed": {"de": "Urkunde", "en": "Deed", "cs": "Listina"},
    "photo": {"de": "Fotografie", "en": "Photograph", "cs": "Fotografie"},
    "census": {"de": "Volkszählung", "en": "Census", "cs": "Sčítání lidu"},
    "map": {"de": "Karte", "en": "Map", "cs": "Mapa"},
    "periodical": {"de": "Periodikum", "en": "Periodical", "cs": "Periodikum"},
    "amtsbuch": {"de": "Amtsbuch", "en": "Official book", "cs": "Úřední kniha"},
}

TYPE_PATTERNS = [
    {
        "key": "registration_slip",
        "de": "Meldezettel",
        "en": "Registration slip",
        "cs": "Přihlašovací lístek",
        "aliases": [
            "meldezettel",
            "registration slip",
            "residence registration slip",
            "přihlašovací lístek",
            "prihlasovaci listek",
        ],
    },
    {
        "key": "municipal_chronicle",
        "de": "Gemeindechronik",
        "en": "Municipal chronicle",
        "cs": "Obecní kronika",
        "aliases": [
            "chronik der gemeinde",
            "gemeindechronik",
            "obecní kronika",
            "municipal chronicle",
            "chronicle of the municipality",
        ],
    },
    {
        "key": "town_chronicle",
        "de": "Stadtchronik",
        "en": "Town chronicle",
        "cs": "Městská kronika",
        "aliases": ["chronik der stadt", "stadtchronik", "městská kronika", "town chronicle", "city chronicle"],
    },
    {
        "key": "school_chronicle",
        "de": "Schulchronik",
        "en": "School chronicle",
        "cs": "Školní kronika",
        "aliases": [
            "schulchronik",
            "chronik der volksschule",
            "chronik der schule",
            "školní kronika",
            "school chronicle",
        ],
    },
    {
        "key": "church_chronicle",
        "de": "Kirchenchronik",
        "en": "Church chronicle",
        "cs": "Církevní kronika",
        "aliases": ["kirchenchronik", "církevní kronika", "church chronicle", "parish chronicle"],
    },
    {
        "key": "local_school_chronicle",
        "de": "Orts- und Schulchronik",
        "en": "Local and school chronicle",
        "cs": "Místní a školní kronika",
        "aliases": ["orts- und schulchronik", "místní a školní kronika", "local and school chronicle"],
    },
    {
        "key": "school_municipal_chronicle",
        "de": "Schul- und Gemeindechronik",
        "en": "School and municipal chronicle",
        "cs": "Školní a obecní kronika",
        "aliases": ["schul- und gemeindechronik", "školní a obecní kronika", "school and municipal chronicle"],
    },
    {
        "key": "memorial_book",
        "de": "Gedenkbuch",
        "en": "Memorial book",
        "cs": "Pamětní kniha",
        "aliases": ["gedenkbuch", "pamětní kniha", "pametni kniha", "memorial book"],
    },
    {
        "key": "yearbook",
        "de": "Chronologisches Jahrbuch",
        "en": "Chronological yearbook",
        "cs": "Chronologická ročenka",
        "aliases": ["chronologisches jahrbuch", "chronologická ročenka", "chronological yearbook"],
    },
    {
        "key": "chronicle_material",
        "de": "Stoffsammlung für Gemeindechronik",
        "en": "Source collection for municipal chronicle",
        "cs": "Materiál pro obecní kroniku",
        "aliases": [
            "stoffsammlung für gemeindechronik",
            "material pro obecni kroniku",
            "materiál pro obecní kroniku",
            "source collection for municipal chronicle",
        ],
    },
    {
        "key": "birth_register",
        "de": "Geburtsmatrik",
        "en": "Birth register",
        "cs": "Matrika narozených",
        "aliases": [
            "geburtsmatrik",
            "matrika narozených",
            "matrika narozenych",
            "birth register",
            "matrika narozenych obsahuje",
        ],
    },
    {
        "key": "marriage_register",
        "de": "Trauungsmatrik",
        "en": "Marriage register",
        "cs": "Matrika oddaných",
        "aliases": ["trauungsmatrik", "matrika oddaných", "matrika oddanych", "marriage register"],
    },
    {
        "key": "death_register",
        "de": "Sterbematrik",
        "en": "Death register",
        "cs": "Matrika zemřelých",
        "aliases": ["sterbematrik", "matrika zemřelých", "matrika zemrelych", "death register"],
    },
    {
        "key": "birth_index",
        "de": "Geburtsindex",
        "en": "Birth index",
        "cs": "Index narozených",
        "aliases": ["geburtsindex", "index narozených", "index narozenych", "birth index"],
    },
    {
        "key": "marriage_index",
        "de": "Trauungsindex",
        "en": "Marriage index",
        "cs": "Index oddaných",
        "aliases": ["trauungsindex", "index oddaných", "index oddanych", "marriage index"],
    },
    {
        "key": "death_index",
        "de": "Sterbeindex",
        "en": "Death index",
        "cs": "Index zemřelých",
        "aliases": ["sterbeindex", "index zemřelých", "index zemrelych", "death index"],
    },
    {
        "key": "land_register",
        "de": "Grundbuch",
        "en": "Land register",
        "cs": "Pozemková kniha",
        "aliases": ["grundbuch", "land register", "pozemková kniha", "pozemkova kniha"],
    },
    {
        "key": "urbar",
        "de": "Urbar",
        "en": "Urbar",
        "cs": "Urbář",
        "aliases": ["urbar", "urbář", "urbarium"],
    },
    {
        "key": "mannschaftsbuch",
        "de": "Mannschaftsbuch",
        "en": "Mannschaftsbuch",
        "cs": "Manschaftní kniha",
        "aliases": ["mannschaftsbuch", "manschaftní kniha", "manschaftni kniha"],
    },
    {
        "key": "stadtbuch",
        "de": "Stadtbuch",
        "en": "Town book",
        "cs": "Městská kniha",
        "aliases": ["stadtbuch", "town book", "městská kniha", "mestska kniha"],
    },
    {
        "key": "ratsprotokoll",
        "de": "Ratsprotokoll",
        "en": "Council minutes",
        "cs": "Radní protokol",
        "aliases": ["ratsprotokoll", "council minutes", "radní protokol", "radni protokol"],
    },
    {
        "key": "briefprotokoll",
        "de": "Briefprotokoll",
        "en": "Letter protocol",
        "cs": "Listovní protokol",
        "aliases": ["briefprotokoll", "letter protocol", "listovní protokol", "listovni protokol"],
    },
    {
        "key": "border_map",
        "de": "Grenzkarte",
        "en": "Border map",
        "cs": "Hraniční mapa",
        "aliases": ["grenzkarte", "border map", "hraniční mapa", "hranicni mapa"],
    },
    {
        "key": "water_map",
        "de": "Wasserkarte",
        "en": "Water map",
        "cs": "Vodní mapa",
        "aliases": ["wasserkarte", "water map", "vodní mapa", "vodni mapa"],
    },
    {
        "key": "road_map",
        "de": "Straßenkarte",
        "en": "Road map",
        "cs": "Silniční mapa",
        "aliases": ["straßenkarte", "strassenkarte", "road map", "silniční mapa", "silnicni mapa"],
    },
    {
        "key": "school_map",
        "de": "Schulkarte",
        "en": "School map",
        "cs": "Školní mapa",
        "aliases": ["schulkarte", "school map", "školní mapa", "skolni mapa"],
    },
    {
        "key": "city_plan",
        "de": "Stadtplan",
        "en": "City plan",
        "cs": "Plán města",
        "aliases": ["plan der stadt", "stadtplan", "city plan", "plán města", "plan mesta"],
    },
    {
        "key": "district_map",
        "de": "Bezirkskarte",
        "en": "District map",
        "cs": "Mapa okresu",
        "aliases": ["karte des bezirks", "bezirkskarte", "district map", "mapa okresu"],
    },
    {
        "key": "spa_list",
        "de": "Kurliste",
        "en": "Spa list",
        "cs": "Kurlist",
        "aliases": ["kurliste", "kurlist", "spa list"],
    },
    {
        "key": "address_book",
        "de": "Adressbuch",
        "en": "Address book",
        "cs": "Adresář",
        "aliases": ["adressbuch", "address book", "adresář", "adresar"],
    },
    {
        "key": "deed",
        "de": "Urkunde",
        "en": "Deed",
        "cs": "Listina",
        "aliases": ["urkunde", "deed", "listina"],
    },
    {
        "key": "photograph",
        "de": "Fotografie",
        "en": "Photograph",
        "cs": "Fotografie",
        "aliases": ["fotografie", "photo", "photograph", "foto"],
    },
    {
        "key": "census",
        "de": "Volkszählung",
        "en": "Census",
        "cs": "Sčítání lidu",
        "aliases": ["volkszählung", "volkszahlung", "census", "sčítání lidu", "scitani lidu"],
    },
    {
        "key": "periodical",
        "de": "Periodikum",
        "en": "Periodical",
        "cs": "Periodikum",
        "aliases": ["periodikum", "periodical"],
    },
    {
        "key": "map",
        "de": "Karte",
        "en": "Map",
        "cs": "Mapa",
        "aliases": ["karte", "map", "mapa", "plan"],
    },
]

REGISTER_CODE_PATTERNS = [
    ("birth_index", re.compile(r"(^|[\s,;:()\[\]-])\*i(?=$|[\s,;:()\[\]-])", re.IGNORECASE)),
    ("marriage_index", re.compile(r"(^|[\s,;:()\[\]-])ooi(?=$|[\s,;:()\[\]-])", re.IGNORECASE)),
    ("death_index", re.compile(r"(^|[\s,;:()\[\]-])\+i(?=$|[\s,;:()\[\]-])", re.IGNORECASE)),
    ("birth_register", re.compile(r"(^|[\s,;:()\[\]-])\*(?!i)(?=$|[\s,;:()\[\]-])")),
    ("marriage_register", re.compile(r"(^|[\s,;:()\[\]-])oo(?!i)(?=$|[\s,;:()\[\]-])", re.IGNORECASE)),
    ("death_register", re.compile(r"(^|[\s,;:()\[\]-])\+(?!i)(?=$|[\s,;:()\[\]-])")),
]
